version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: numerus_agent_app
    ports:
      - "3000:3000"
    volumes:
      # Mount local code (excluding node_modules and build artifacts)
      - .:/app
      # Use named volumes for better performance/stability on Windows
      - node_modules_data:/app/node_modules
      - nuxt_build_data:/app/.nuxt
      - nuxt_output_data:/app/.output
    environment:
      - NODE_ENV=development
    # Command is defined in Dockerfile CMD

# Define the named volumes
volumes:
  node_modules_data:
  nuxt_build_data:
  nuxt_output_data: 